CODE = LEFT_PAR LIST_WORDS RIGHT_PAR ();
WORD = RULE_NAME ()
	   CODE ()
	   ASSIGN ()
	   SPECIAL ()
	   END ();
LIST_WORDS = WORD LIST_WORDS ()
			 NONE ();
RULE = RULE_NAME ()
	   ASSIGN ()
	   LIST_RULE_DEF ()
	   END ();
RULE_DEF = LIST_NAME CODE ();
MAIN = RULE MAIN ()
	   CODE ();
LIST_RULE_DEF = RULE_DEF LIST_RULE_DEF ()
				NONE ();
LIST_NAME = RULE_NAME LIST_NAME ()
			NONE ();
()
