[package]
name = "game_of_life"
version = "0.1.0"
edition = "2018"
license = "Mozilla Public License"
authors = ["Damien Lejosne <damlejo6445@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Dalejosne/Automata/ree/main/game_of_life"
description = "A nice game of life package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
